name: Label Studio Enterprise AMP
description: "Professional image and text labeling tool. Isolated venv and secure networking for CML."
author: "smerchanmole"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
  MY_SUBDOMAIN:
    description: "Unique subdomain for your Label Studio instance"
    default: "labelstudioCAI"
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: start_application
    name: Label Studio App
    subdomain: ${MY_SUBDOMAIN}
    script: launch.py
    kernel: python3
    short_summary: "Main Label Studio interface"
    long_summary: "Launch the Label Studio web interface on the assigned port."
    cpu: 4
    memory: 8
