name: Label Studio Enterprise AMP
description: "Professional image and text labeling tool. Isolated venv and secure networking for CML."
author: "smerchanmole"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
  MY_SUBDOMAIN:
    description: "Unique subdomain for your Label Studio instance"
    default: "labelstudioCAI"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: launch.py
    short_summary: "Initial setup of isolated venv"
    kernel: Python 3.10
    cpu: 2
    memory: 4

  - type: start_application
    name: Label Studio App
    subdomain: labelstudioCAI
    script: launch.py
    short_summary: "Main Label Studio interface"
    long_summary: "Launch the Label Studio web interface on the assigned port."
    cpu: 4
    memory: 8
